version : "3.7"

services :
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: "laravel_db"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_PASSWORD: ""

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www/html


